version: "3.9"

volumes:
    db-store:
    test-db-store:

services:
    app:
        build: ./docker/app
        user: ${UID}:${GID}
        volumes:
            - ./src:/data

    web:
        build: ./docker/web
        ports:
            - 8080:80
        volumes:
            - ./src:/data
        working_dir: /data

    test_db:
        build: ./docker/db
        volumes:
            - test-db-store:/var/lib/mysql
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=multiauthdb
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=dbpassword
            - TZ=Asia/Tokyo
    db:
        build: ./docker/db
        volumes:
            - db-store:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=multiauthdb
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=dbpassword
            - TZ=Asia/Tokyo
